### ISSUE TITLE
Gateway crash setting Node Description in JMRI

### ISSUE THREAD

**Issue by ggee** [manu-fwi/openlcb-gateway#12]
When trying to set a User Defined Node Description in JMRI Node Configuration dialog, the gateway crashes.

```
new msg= :X1BDBCE44N200000000040FB66;
datagram received ok sent ---> b':X19A28DBCN0E44;'
memory write
datagram received ok sent ---> :X19A28DBCN0E44;
66
written: b'f'
node: 2002004 memory write 251 offset 64
set_mem_partial 64 b'f'
off= 0 size= 1 content= b'M'
off= 1 size= 63 content= bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
off= 64 size= 64 content= bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
None
found 64 64 b'f' 1
new msg= :X1DDBCE44N64676400;
Traceback (most recent call last):
  File "openlcb_gateway.py", line 446, in <module>
    process_grid_connect(c,msg)
  File "openlcb_gateway.py", line 420, in process_grid_connect
    process_datagram(cli,msg)
  File "openlcb_gateway.py", line 369, in process_datagram
    address = int(msg[15:23],16)
ValueError: invalid literal for int() with base 16: '6400;'

```

**Comment by manu-fwi** [comment]
I just commited a fix for that (and the other one about the node name). Please test.
