### ISSUE TITLE
RR_duino_net_serial.py: Startup fails.

### ISSUE THREAD

**Issue by ggee** [manu-fwi/openlcb-gateway#7]
Get error when starting RR_duino_net_serial.py

```
pi@RPi-JMRI:~/openlcb-gateway $ python3 ./RR_duino_net_serial.py
RR_duino_net_serial started on serial port /dev/ttyACM0 at 115200
Connected to serial port /dev/ttyACM0
loading RR_duino nodes from RR_duino_nodes_DB.cfg
Traceback (most recent call last):
  File "./RR_duino_net_serial.py", line 286, in <module>
    load_nodes()
  File "./RR_duino_net_serial.py", line 224, in load_nodes
    answer = send_msg(RR_duino.RR_duino_message.build_version_cmd(fullID_add[fullID]))
  File "./RR_duino_net_serial.py", line 201, in send_msg
    poll_net()
  File "./RR_duino_net_serial.py", line 173, in poll_net
    buf=s.recv(200).decode('utf-8') #byte array: the raw cmri message
OSError: [Errno 107] Transport endpoint is not connected

```

**Comment by ggee** [comment]
Changed file as per Manu instructions.

`Can you move load_nodes() on mine 286 of RR duino net serial.py to line 301. Thalys should get you going.
`

**Comment by manu-fwi** [comment]
Perfect
